import { formatCurrency, formatDate } from "@/lib/format";
import { PaymentType } from "@/types/payment";
import { ProjectType } from "@/types/project";

const BRAND_INK: [number, number, number] = [28, 37, 65];
const BRAND_BLUE: [number, number, number] = [61, 90, 254];
const BRAND_MUTED: [number, number, number] = [102, 112, 133];

async function loadJsPdf() {
  const { jsPDF } = await import("jspdf");
  return jsPDF;
}

function drawLetterhead(doc: InstanceType<Awaited<ReturnType<typeof loadJsPdf>>>, title: string) {
  doc.setFillColor(...BRAND_BLUE);
  doc.rect(0, 0, 210, 22, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text("Project Pay", 16, 14);

  doc.setTextColor(...BRAND_INK);
  doc.setFontSize(20);
  doc.text(title, 16, 36);
}

function drawFooter(doc: InstanceType<Awaited<ReturnType<typeof loadJsPdf>>>) {
  doc.setTextColor(...BRAND_MUTED);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text("Generated by Project Pay — this document is not a tax invoice.", 16, 285);
}

type ReceiptProject = Pick<ProjectType, "name" | "clientName"> & { projectCode?: string };

export async function downloadPaymentReceipt(payment: PaymentType, project: ReceiptProject) {
  const jsPDF = await loadJsPdf();
  const doc = new jsPDF();

  drawLetterhead(doc, "Payment Receipt");

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(...BRAND_INK);

  const rows: [string, string][] = [
    ["Project", project.name],
    ["Project code", project.projectCode ?? "—"],
    ["Client", project.clientName],
    ["Transaction ID", payment.transactionId],
    ["Payment date", formatDate(payment.paymentDate)],
    ["Payment method", payment.paymentMethod],
    ["Amount received", formatCurrency(payment.paymentAmount)],
  ];

  let y = 52;
  for (const [label, value] of rows) {
    doc.setTextColor(...BRAND_MUTED);
    doc.text(label, 16, y);
    doc.setTextColor(...BRAND_INK);
    doc.text(value, 80, y);
    y += 9;
  }

  drawFooter(doc);
  doc.save(`receipt-${payment.transactionId || payment._id || "payment"}.pdf`);
}

export async function downloadProjectInvoice(project: ProjectType) {
  const jsPDF = await loadJsPdf();
  const doc = new jsPDF();

  drawLetterhead(doc, "Project Invoice");

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);

  const rows: [string, string][] = [
    ["Project", project.name],
    ["Project code", project.projectCode ?? "—"],
    ["Client", project.clientName],
    ["Client email", project.clientEmail],
    ["Client phone", project.clientPhone],
    ["Start date", formatDate(project.startDate)],
    ["End date", formatDate(project.endDate)],
  ];

  let y = 52;
  for (const [label, value] of rows) {
    doc.setTextColor(...BRAND_MUTED);
    doc.text(label, 16, y);
    doc.setTextColor(...BRAND_INK);
    doc.text(value, 80, y);
    y += 9;
  }

  y += 4;
  doc.setDrawColor(...BRAND_MUTED);
  doc.line(16, y, 194, y);
  y += 10;

  const totals: [string, string][] = [
    ["Total budget", formatCurrency(project.budget)],
    ["Advance received", formatCurrency(project.advance)],
    ["Total paid", formatCurrency(project.totalPaid ?? 0)],
    ["Balance due", formatCurrency(project.due ?? 0)],
  ];

  for (const [label, value] of totals) {
    doc.setTextColor(...BRAND_MUTED);
    doc.text(label, 16, y);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...BRAND_INK);
    doc.text(value, 80, y);
    doc.setFont("helvetica", "normal");
    y += 9;
  }

  drawFooter(doc);
  doc.save(`invoice-${project.projectCode ?? project.name}.pdf`);
}
